#!/usr/bin/env bash

# script/cipackage - packages the build artefacts for publishing

# exit on sub-module failure
set -e

# move to parent dir as CI should have set PWD to be $repo/script
cd "$(dirname "$0")/.."

# ------

echo "Packaging.."
date "+%H:%M:%S"
echo ""

echo "--------- "
